name: terraform-ci
on:
  pull_request:
permissions:
  actions: read
  checks: read
  contents: read
  pull-requests: write
  security-events: write

jobs:
  ci:
    uses: SPHTech-Platform/reusable-workflows/.github/workflows/terraform.yaml@main
    with:
      upload_sarif: false
      checkov_skip_check: CKV_TF_1,CKV_AWS_338
